# Generated by Django 2.0.7 on 2019-04-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_hospital_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('hospital_lat', models.CharField(max_length=1000)),
                ('hospital_lon', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_OPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('cardio_t1', models.CharField(max_length=10)),
                ('cardio_t2', models.CharField(max_length=10)),
                ('neuro_t1', models.CharField(max_length=10)),
                ('neuro_t2', models.CharField(max_length=10)),
                ('ortho_t1', models.CharField(max_length=10)),
                ('ortho_t2', models.CharField(max_length=10)),
                ('dent_t1', models.CharField(max_length=10)),
                ('dent_t2', models.CharField(max_length=10)),
                ('gen_t1', models.CharField(max_length=10)),
                ('gen_t2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Wards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('emer_w', models.IntegerField()),
                ('cardio_w', models.IntegerField()),
                ('neuro_w', models.IntegerField()),
                ('ortho_w', models.IntegerField()),
                ('gen_w', models.IntegerField()),
            ],
        ),
    ]
